### PR TITLE
Fix up spec file and Makefile to build rpm packages

### PR DESCRIPTION
**Pull request by rhatdan**
In order to get through Fedora Package system, we have to have an
approved container-storage-setup spec file and rpm.  These changes
allow us to build the rpm and begin going through the package
review.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@lsm5 PTAL

**Comment by rhatdan** [comment]
@rhvgoyal Beginning the process to go through Fedora Review.

make rpm 

Should create an installable rpm package.

**Comment by rhvgoyal** [comment]
LGTM

**Comment by rhvgoyal** [comment]
@rh-atomic-bot r+

**Comment by rhvgoyal** [comment]
@rh-atomic-bot r+ 6ec7555

**Comment by rhatdan** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1427295

**Pull request closed without merging**
