### PR TITLE
Rewrite the README to fully explain what container-storage-setup is

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhvgoyal** [comment]
I am not sure about the idea of copying all the info from man page or config file in this page. Just providing
links should be enough. Otherwise we will have now 3 places to update for any documentation change.

We already have a link to man page in the doc and that seems to do a reasonable job.

**Comment by rhatdan** [comment]
I would like to experiment with writing the man page as a markdown, and then some how have it in the README and the man page.

The problem with the README, now is it does not describe enough to make it interesting.

**Comment by rhatdan** [comment]
Is there a way to link to the man page from the README, that would also be cool.

**Comment by rhvgoyal** [comment]
May be we should put in a simple example also there to quickly demonstrate what it can do. That should make it little more interesting.

**Comment by rhvgoyal** [comment]
@rhatdan we already have a link to man page in README at the bottom.

**Comment by rhatdan** [comment]
Perhaps if it was written in Markdown, that would be better.

Take a look at:
https://github.com/docker/docker/blob/master/man/docker-run.1.md

**Comment by rhatdan** [comment]
But Anyways it is probably better to discuss what the README should look like in a google doc.

**Comment by rhvgoyal** [comment]
How would man utility parse a man page written in md. Does it already do it?

**Comment by rhatdan** [comment]
The is a tool go-md2man that converts from markdown to nroff format, you would do this during make install

**Comment by rhvgoyal** [comment]
So then we will have to create a dependency on this go-md2man tool. I am not sure which rpm/package provides that tool.

**Comment by rhvgoyal** [comment]
How about keeping it simple for now. That is enhance existing README to explain what this project is all about with a simple example. And then provide a link to man page.

And converting man page to md can be a separate conversation in a separate PR?

**Comment by rhatdan** [comment]
Sure.  go-md2man is shipped as an rpm in Fedora/Centos and RHEL.  It is needed for building docker and some other packages, but I am fine with removing it.  I sent you a link to the google doc to quickly finish the README.

**Comment by rhvgoyal** [comment]
@rh-atomic-bot r+ 79462e9

**Pull request closed without merging**
