### PR TITLE
Miscellaneous cleanup 1

### PR DESCRIPTION
**Pull request by rhvgoyal**
Few patches to do miscellaneous cleanup. Primarily trying to move some code from mainline into functions.

Also allow using deprecated options only in compatibility mode and not outside it.

### CODE REVIEW

**Comment by rhvgoyal** [comment]
@rhatdan @shishir-a412ed PTAL

**Comment by rhatdan** [comment]
:+1:

**Comment by rhvgoyal** [comment]
@rhatdan I should treat that thumbs up as LGTM?

**Comment by rhatdan** [comment]
Yes that is a Visual LGTM Enter ":" and it shows up. It's what the cook kids use.

**Comment by rhvgoyal** [comment]
@rh-atomic-bot r+ 781cbce

**Pull request closed without merging**
