### PR TITLE
Bump up version to 0.10.0

### PR DESCRIPTION
**Pull request by rhvgoyal**
GPT support has been added. Bump up version for that.

Signed-off-by: Vivek Goyal <vgoyal@redhat.com>

### CODE REVIEW

**Comment by rhvgoyal** [comment]
cc @rhatdan

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@lsm5 @fkluknav we need new versions of docker for Rawhide and f28 as well as RHEL

**Comment by rhvgoyal** [comment]
@rh-atomic-bot r+ 322b8e5

**Comment by lsm5** [comment]
On Mon, Apr 30, 2018 at 01:42:39PM -0700, Daniel J Walsh wrote:
> @lsm5 @fkluknav we need new versions of docker for Rawhide and f28 as well as RHEL
> 

just double-checking, new version of c-s-s and not docker, yes? Any change
needed to the docker side?

@fkluknav could you please take care of this?

-- 
Lokesh
IRC: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by rhatdan** [comment]
No, @rhvgoyal Correct?

**Comment by rhvgoyal** [comment]
No changes should be required to docker. updating container-storage-setup should be enough.

**Pull request merged**
