### PR TITLE
Bump up version to 0.8.0

### PR DESCRIPTION
**Pull request by rhvgoyal**
atomic folks want changes introduced to ROOT_SIZE. Hence bumping up version
for new build.

Signed-off-by: Vivek Goyal <vgoyal@redhat.com>

### CODE REVIEW

**Comment by rhvgoyal** [comment]
Just a version change. Merging it.

**Comment by rhatdan** [comment]
LGTM

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ bb1d109

**Comment by rhatdan** [comment]
@cgwalters I will rebuild a package for this for F26, f27, Rawhide.

**Comment by jlebon** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
